#! /bin/sh
#
#  Start / Stop the MvLogServer daemon.
#
# chkconfig: 2345 90 60
# description: MvLogServer

### BEGIN INIT INFO
# Provides:          MvLogServer
# Required-Start:    $remote_fs $syslog $local_fs
# Required-Stop:     $remote_fs $syslog $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start hik log server at boot time
# Description:       HikLogServer is a daemon to self-startint log server.
### END INIT INFO
# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0



DAEMON="/opt/MVS/logserver/MvLogServer"
NAME="MvLogServer"
PIDFILE="/var/run/MvLogServer.pid"

start () {
	if [ $UID -ne 0 ] ; then
		echo "User has insufficient privileges."
		exit 4
	fi
    	#[ -x $DAEMON ] || exit 5

	echo -n "Starting $NAME: "
   	daemon $DAEMON
 	RETVAL=$?
	echo
	[ $RETVAL = 0 ]
	return 0
}

stop () {
	if [ $UID -ne 0 ] ; then
		echo "User has insufficient privileges."
		exit 4
	fi

	# stop daemon
	echo -n $"Stopping $NAME: "
	killproc $NAME
	RETVAL=$?
	echo
	[ $RETVAL = 0 ]
	return 0
}

restart() {
	stop
	sleep 1
	start	
	return 0
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
	status)
		status -p $PIDFILE $NAME
		RETVAL=$?
        ;;
	*)

	echo $"Usage: $NAME {start|stop|restart|status}" 
	exit 2
esac

exit $RETVAL